# ===============================================================================
# ENRICHED POPULATION COST-EFFECTIVENESS ANALYSIS
# ===============================================================================
# Calculates ICERs for a "ceiling scenario" where only biomarker-positive
# patients are considered. For each economic biomarker strategy:
#   - Experimental arm: biomarker-positive patients on FLOX + nivolumab
#   - Control arm: biomarker-positive patients on FLOX only
#
# This is an apples-to-apples comparison within the enriched biomarker-positive
# cohort, as in a biomarker-enriched trial design where only positive patients
# are enrolled.
#
# Biomarker-positive experimental curves already exist in l_params_base.
# Biomarker-positive control curves are generated by predicting from the fitted
# single joint survival model for positive patients assigned to control treatment.
#
# Economic biomarkers are defined by get_biomarkers(); TLR is not included.
#
# Prerequisites:
#   - 02_setup_and_global_variables.R (global vars)
#   - 03_biomarker_strategies.R (biomarker definitions)
#   - 06/07 are re-sourced once by run_enriched_analysis()
# ===============================================================================

if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(here, dampack, dplyr, flexsurv)

source(here::here("scripts/R/functions/model_fun.R"))
source(here::here("scripts/R/functions/calculate_outcomes.R"))
source(here::here("scripts/R/functions/cea_helpers.R"))
source(here::here("scripts/R/functions/prediction_functions.R"))

# ===============================================================================
# HELPER FUNCTIONS
# ===============================================================================

#' Refresh survival fits and base-case inputs for the single model
#'
#' Re-sources scripts 06 and 07 once so data_complete, models, time_points, and
#' l_params_base are synchronized before enriched counterfactual curves are made.
refresh_single_model_inputs <- function(verbose = TRUE) {
  if (verbose) {
    cat("Refreshing survival fits and base-case inputs for the single model...\n")
  }

  suppressMessages(suppressWarnings(
    source(here::here("scripts/R/analysis/04_parametric_survival_analysis.R"))
  ))

  suppressMessages(suppressWarnings(
    source(here::here("scripts/R/analysis/05_basecase_input_parameters.R"))
  ))
}

#' Generate survival curves for biomarker-positive patients on control treatment
#'
#' @param biomarker_name Character: "crp" or "tmb_braf"
#' @return List with $os and $pfs vectors (population-averaged survival curves)
generate_enriched_control_curves <- function(biomarker_name) {

  if (!exists("data_complete", inherits = TRUE) ||
      !exists("models", inherits = TRUE) ||
      !exists("time_points", inherits = TRUE)) {
    stop("data_complete, models, and time_points must exist. Run refresh_single_model_inputs() first.")
  }

  if (!biomarker_name %in% get_biomarkers()) {
    stop("Biomarker '", biomarker_name, "' is not an economic biomarker.")
  }

  ctrl_rx <- levels(data_complete$Rx)[1]

  pos_data <- data_complete[as.numeric(as.character(data_complete[[biomarker_name]])) == 1, ]
  if (nrow(pos_data) == 0) {
    stop("No biomarker-positive patients available for ", biomarker_name)
  }

  pos_data$Rx <- factor(ctrl_rx, levels = levels(data_complete$Rx))

  model_os <- models$best_fit$os
  model_pfs <- models$best_fit$pfs

  if (is.null(model_os) || is.null(model_pfs)) {
    stop("Best-fit OS/PFS models are not available in models$best_fit.")
  }

  os_pred <- predict(model_os, newdata = pos_data,
                     type = "survival", times = time_points)
  pfs_pred <- predict(model_pfs, newdata = pos_data,
                      type = "survival", times = time_points)

  os_matrix <- extract_all_survival_probabilities(os_pred)
  pfs_matrix <- extract_all_survival_probabilities(pfs_pred)

  list(
    os = rowMeans(os_matrix, na.rm = TRUE),
    pfs = rowMeans(pfs_matrix, na.rm = TRUE)
  )
}

#' Run enriched population analysis for the single economic model
#'
#' For each economic biomarker, computes:
#'   - Enriched experimental: biomarker-positive patients on experimental treatment
#'   - Enriched control: biomarker-positive patients on standard treatment
#'   - Enriched ICER: (exp_cost - ctrl_cost) / (exp_effect - ctrl_effect)
#'
#' @param verbose Logical, print progress messages
#' @return List with base and enriched results
run_enriched_analysis <- function(verbose = TRUE) {

  refresh_single_model_inputs(verbose = verbose)

  base_result <- run_basecase(verbose = verbose)
  base_pairwise <- calculate_pairwise_icers(base_result$base_results)

  if (verbose) {
    cat("Generating enriched population curves (biomarker-positive control)...\n")
  }

  weights <- discount_weights(l_params_base, time_horizon + 1)

  enriched_rows <- list()

  for (biomarker in get_biomarkers()) {

    os_exp <- l_params_base$p_os[[paste0(biomarker, "_pos_OS")]]
    pfs_exp <- l_params_base$p_pfs[[paste0(biomarker, "_pos_PFS")]]
    states_exp <- partitioned_survival_states(
      os_exp, pfs_exp, paste0("enriched ", biomarker, "+ experimental")
    )

    exp_outcomes <- calculate_outcomes(
      params = l_params_base,
      p_pf = states_exp$p_pf,
      p_p = states_exp$p_p,
      p_d = states_exp$p_d,
      treatment_type = "experimental",
      biomarker = biomarker,
      v_dw_c = weights$cost,
      v_dw_e = weights$effect,
      cl = cl
    )

    ctrl_curves <- generate_enriched_control_curves(biomarker)
    states_ctrl <- partitioned_survival_states(
      ctrl_curves$os, ctrl_curves$pfs,
      paste0("enriched ", biomarker, "+ control")
    )

    ctrl_outcomes <- calculate_outcomes(
      params = l_params_base,
      p_pf = states_ctrl$p_pf,
      p_p = states_ctrl$p_p,
      p_d = states_ctrl$p_d,
      treatment_type = "standard",
      biomarker = biomarker,
      v_dw_c = weights$cost,
      v_dw_e = weights$effect,
      cl = cl
    )

    pairwise <- calculate_pairwise_icers(data.frame(
      Strategy = c(get_control_strategy(), biomarker),
      Cost = c(ctrl_outcomes$costs_total, exp_outcomes$costs_total),
      Effect = c(ctrl_outcomes$qalys_total, exp_outcomes$qalys_total)
    ))[2, ]
    enriched_rows[[biomarker]] <- transform(
      pairwise,
      Ctrl_Cost = ctrl_outcomes$costs_total,
      Ctrl_Effect = ctrl_outcomes$qalys_total
    )
  }

  enriched_pairwise <- do.call(rbind, enriched_rows)
  rownames(enriched_pairwise) <- NULL

  if (verbose) {
    cat("Enriched analysis complete.\n")
  }

  biomarkers <- get_biomarkers()
  base_rows <- base_pairwise[match(biomarkers, base_pairwise$Strategy), ]
  enriched_rows <- enriched_pairwise[match(biomarkers, enriched_pairwise$Strategy), ]
  enriched_comparison <- data.frame(
    Biomarker = unname(strategy_display_name(biomarkers)),
    Prevalence = strategies_df$prevalence[match(biomarkers, strategies_df$id)],
    Base_Cost = base_rows$Cost, Base_Effect = base_rows$Effect,
    Base_ICER = base_rows$ICER, Base_Status = base_rows$Status,
    Enr_Cost = enriched_rows$Cost, Enr_Effect = enriched_rows$Effect,
    Enr_Ctrl_Cost = enriched_rows$Ctrl_Cost,
    Enr_Ctrl_Effect = enriched_rows$Ctrl_Effect,
    Enr_ICER = enriched_rows$ICER, Enr_Status = enriched_rows$Status,
    Pct_Change = ifelse(
      base_rows$Status == "Non-dominated" &
        enriched_rows$Status == "Non-dominated" &
        is.finite(base_rows$ICER) & base_rows$ICER != 0 &
        is.finite(enriched_rows$ICER),
      (enriched_rows$ICER - base_rows$ICER) / abs(base_rows$ICER) * 100,
      NA_real_
    )
  )

  list(
    base_results = base_result$base_results,
    base_pairwise = base_pairwise,
    base_icer_obj = base_result$icer_obj,
    enriched_pairwise = enriched_pairwise,
    comparison = enriched_comparison,
    model_config = base_result$model_config
  )
}

# ===============================================================================
# MAIN EXECUTION
# ===============================================================================

cat("\n")
cat(rep("=", 80), "\n", sep = "")
cat("ENRICHED POPULATION COST-EFFECTIVENESS ANALYSIS\n")
cat("Biomarker-positive experimental vs biomarker-positive control\n")
cat(rep("=", 80), "\n", sep = "")

enriched_results <- run_enriched_analysis(verbose = TRUE)
enriched_comparison <- enriched_results$comparison
