# ===============================================================================
# ENRICHED POPULATION COST-EFFECTIVENESS ANALYSIS
# ===============================================================================
# Calculates ICERs for a "ceiling scenario" where only biomarker-positive
# patients are considered. For each economic biomarker strategy:
#   - Experimental arm: biomarker-positive patients on FLOX + nivolumab
#   - Control arm: biomarker-positive patients on FLOX only
#
# This is an apples-to-apples comparison within the enriched biomarker-positive
# cohort, as in a biomarker-enriched trial design where only positive patients
# are enrolled.
#
# Biomarker-positive experimental curves already exist in l_params_base.
# Biomarker-positive control curves are generated by predicting from the fitted
# single joint survival model for positive patients assigned to control treatment.
#
# Economic biomarkers are defined by get_biomarkers(); TLR is not included.
#
# Prerequisites:
#   - 02_setup_and_global_variables.R (global vars)
#   - 03_biomarker_strategies.R (biomarker definitions)
#   - 06/07 are re-sourced once by run_enriched_analysis()
# ===============================================================================

if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(here, dampack, dplyr, scales, flexsurv)

source(here::here("scripts/R/functions/model_fun.R"))
source(here::here("scripts/R/functions/calculate_outcomes.R"))
source(here::here("scripts/R/functions/cea_helpers.R"))
source(here::here("scripts/R/functions/prediction_functions.R"))

# ===============================================================================
# HELPER FUNCTIONS
# ===============================================================================

#' Calculate simple pairwise ICERs (each strategy vs control)
#'
#' @param results Data frame with Strategy, Cost, Effect columns from model_fun()
#' @return Data frame with pairwise incremental costs, effects, ICERs, and status
calculate_pairwise_icers <- function(results) {
  control_cost <- results$Cost[results$Strategy == "control"]
  control_effect <- results$Effect[results$Strategy == "control"]

  if (length(control_cost) != 1 || length(control_effect) != 1) {
    stop("Control strategy must appear exactly once in model results.")
  }

  pairwise_df <- data.frame(
    Strategy = results$Strategy,
    Cost = results$Cost,
    Effect = results$Effect,
    Inc_Cost = results$Cost - control_cost,
    Inc_Effect = results$Effect - control_effect,
    stringsAsFactors = FALSE
  )

  pairwise_df$ICER <- ifelse(
    pairwise_df$Strategy == get_control_strategy(),
    NA_real_,
    pairwise_df$Inc_Cost / pairwise_df$Inc_Effect
  )

  pairwise_df$Status <- ifelse(
    pairwise_df$Strategy == "control",
    "Reference",
    ifelse(pairwise_df$Inc_Cost > 0 & pairwise_df$Inc_Effect <= 0,
           "Dominated",
           ifelse(pairwise_df$Inc_Cost < 0 & pairwise_df$Inc_Effect > 0,
                  "Cost-saving",
                  "Non-dominated"))
  )

  pairwise_df
}

#' Get display labels for economic biomarkers
#'
#' @param biomarkers Character vector of biomarker IDs
#' @return Character vector of display labels
get_biomarker_labels <- function(biomarkers) {
  label_map <- strategy_display_name(get_biomarkers())

  unname(ifelse(
    biomarkers %in% names(label_map),
    label_map[biomarkers],
    biomarkers
  ))
}

#' Refresh survival fits and base-case inputs for the single model
#'
#' Re-sources scripts 06 and 07 once so data_complete, models, time_points, and
#' l_params_base are synchronized before enriched counterfactual curves are made.
refresh_single_model_inputs <- function(verbose = TRUE) {
  if (verbose) {
    cat("Refreshing survival fits and base-case inputs for the single model...\n")
  }

  suppressMessages(suppressWarnings(
    source(here::here("scripts/R/analysis/04_parametric_survival_analysis.R"))
  ))

  suppressMessages(suppressWarnings(
    source(here::here("scripts/R/analysis/05_basecase_input_parameters.R"))
  ))
}

#' Generate survival curves for biomarker-positive patients on control treatment
#'
#' @param biomarker_name Character: "crp" or "tmb_braf"
#' @return List with $os and $pfs vectors (population-averaged survival curves)
generate_enriched_control_curves <- function(biomarker_name) {

  if (!exists("data_complete", inherits = TRUE) ||
      !exists("models", inherits = TRUE) ||
      !exists("time_points", inherits = TRUE)) {
    stop("data_complete, models, and time_points must exist. Run refresh_single_model_inputs() first.")
  }

  if (!biomarker_name %in% get_biomarkers()) {
    stop("Biomarker '", biomarker_name, "' is not an economic biomarker.")
  }

  ctrl_rx <- levels(data_complete$Rx)[1]

  pos_data <- data_complete[as.numeric(as.character(data_complete[[biomarker_name]])) == 1, ]
  if (nrow(pos_data) == 0) {
    stop("No biomarker-positive patients available for ", biomarker_name)
  }

  pos_data$Rx <- factor(ctrl_rx, levels = levels(data_complete$Rx))

  model_os <- models$best_fit$os
  model_pfs <- models$best_fit$pfs

  if (is.null(model_os) || is.null(model_pfs)) {
    stop("Best-fit OS/PFS models are not available in models$best_fit.")
  }

  os_pred <- predict(model_os, newdata = pos_data,
                     type = "survival", times = time_points)
  pfs_pred <- predict(model_pfs, newdata = pos_data,
                      type = "survival", times = time_points)

  os_matrix <- extract_all_survival_probabilities(os_pred)
  pfs_matrix <- extract_all_survival_probabilities(pfs_pred)

  list(
    os = rowMeans(os_matrix, na.rm = TRUE),
    pfs = rowMeans(pfs_matrix, na.rm = TRUE)
  )
}

#' Compute state occupancy from survival curves with constraints
#'
#' @param os OS survival vector
#' @param pfs PFS survival vector
#' @param label Label for warning messages
#' @return List with p_pf, p_p, p_d vectors
compute_state_occupancy <- function(os, pfs, label = "") {
  pfs <- pmin(pfs, os)

  p_pf <- pfs
  p_p <- pmax(os - pfs, 0)
  p_d <- 1 - os

  p_pf[1] <- 1.0
  p_p[1] <- 0.0
  p_d[1] <- 0.0

  list(p_pf = p_pf, p_p = p_p, p_d = p_d)
}

#' Run enriched population analysis for the single economic model
#'
#' For each economic biomarker, computes:
#'   - Enriched experimental: biomarker-positive patients on experimental treatment
#'   - Enriched control: biomarker-positive patients on standard treatment
#'   - Enriched ICER: (exp_cost - ctrl_cost) / (exp_effect - ctrl_effect)
#'
#' @param verbose Logical, print progress messages
#' @return List with base and enriched results
run_enriched_analysis <- function(verbose = TRUE) {

  refresh_single_model_inputs(verbose = verbose)

  base_result <- run_basecase(verbose = verbose)
  base_pairwise <- calculate_pairwise_icers(base_result$base_results)

  if (verbose) {
    cat("Generating enriched population curves (biomarker-positive control)...\n")
  }

  v_dw_c <- 1 / (1 + l_params_base$dr_costs)^(seq(0, time_horizon) / 52)
  v_dw_e <- 1 / (1 + l_params_base$dr_effects)^(seq(0, time_horizon) / 52)

  enriched_rows <- list()

  for (biomarker in get_biomarkers()) {

    os_exp <- l_params_base$p_os[[paste0(biomarker, "_pos_OS")]]
    pfs_exp <- l_params_base$p_pfs[[paste0(biomarker, "_pos_PFS")]]
    states_exp <- compute_state_occupancy(os_exp, pfs_exp,
                                          paste0(biomarker, "+ exp"))

    exp_outcomes <- calculate_outcomes(
      params = l_params_base,
      p_pf = states_exp$p_pf,
      p_p = states_exp$p_p,
      p_d = states_exp$p_d,
      treatment_type = "experimental",
      biomarker = biomarker,
      v_dw_c = v_dw_c,
      v_dw_e = v_dw_e,
      cl = cl
    )

    ctrl_curves <- generate_enriched_control_curves(biomarker)
    states_ctrl <- compute_state_occupancy(ctrl_curves$os, ctrl_curves$pfs,
                                           paste0(biomarker, "+ ctrl"))

    ctrl_outcomes <- calculate_outcomes(
      params = l_params_base,
      p_pf = states_ctrl$p_pf,
      p_p = states_ctrl$p_p,
      p_d = states_ctrl$p_d,
      treatment_type = "standard",
      biomarker = biomarker,
      v_dw_c = v_dw_c,
      v_dw_e = v_dw_e,
      cl = cl
    )

    inc_cost <- exp_outcomes$costs_total - ctrl_outcomes$costs_total
    inc_effect <- exp_outcomes$qalys_total - ctrl_outcomes$qalys_total

    status <- if (inc_cost > 0 & inc_effect <= 0) {
      "Dominated"
    } else if (inc_cost < 0 & inc_effect > 0) {
      "Cost-saving"
    } else {
      "Non-dominated"
    }

    enriched_rows[[biomarker]] <- data.frame(
      Strategy = biomarker,
      Cost = exp_outcomes$costs_total,
      Effect = exp_outcomes$qalys_total,
      Ctrl_Cost = ctrl_outcomes$costs_total,
      Ctrl_Effect = ctrl_outcomes$qalys_total,
      Inc_Cost = inc_cost,
      Inc_Effect = inc_effect,
      ICER = inc_cost / inc_effect,
      Status = status,
      stringsAsFactors = FALSE
    )
  }

  enriched_pairwise <- do.call(rbind, enriched_rows)
  rownames(enriched_pairwise) <- NULL

  if (verbose) {
    cat("Enriched analysis complete.\n")
  }

  list(
    base_results = base_result$base_results,
    base_pairwise = base_pairwise,
    base_icer_obj = base_result$icer_obj,
    enriched_pairwise = enriched_pairwise,
    model_config = base_result$model_config
  )
}

# ===============================================================================
# FORMATTING FUNCTIONS
# ===============================================================================

#' Format enriched vs base case comparison table
#'
#' @param result List from run_enriched_analysis()
#' @return Data frame with comparison metrics
format_enriched_comparison_table <- function(result) {

  biomarkers <- get_biomarkers()
  biomarker_labels <- get_biomarker_labels(biomarkers)

  rows <- lapply(seq_along(biomarkers), function(i) {
    bm <- biomarkers[i]

    base_row <- result$base_pairwise[result$base_pairwise$Strategy == bm, ]
    enriched_row <- result$enriched_pairwise[result$enriched_pairwise$Strategy == bm, ]

    if (nrow(base_row) != 1 || nrow(enriched_row) != 1) {
      stop("Could not find base/enriched results for biomarker: ", bm)
    }

    base_icer <- base_row$ICER
    enr_icer <- enriched_row$ICER
    pct_change <- if (base_row$Status == "Non-dominated" &&
                      enriched_row$Status == "Non-dominated" &&
                      !is.na(base_icer) && !is.na(enr_icer) &&
                      base_icer != 0 &&
                      is.finite(base_icer) && is.finite(enr_icer)) {
      (enr_icer - base_icer) / abs(base_icer) * 100
    } else {
      NA_real_
    }

    data.frame(
      Biomarker = biomarker_labels[i],
      Prevalence = strategies_df$prevalence[strategies_df$id == bm],
      Base_Cost = base_row$Cost,
      Base_Effect = base_row$Effect,
      Base_ICER = base_row$ICER,
      Base_Status = base_row$Status,
      Enr_Cost = enriched_row$Cost,
      Enr_Effect = enriched_row$Effect,
      Enr_Ctrl_Cost = enriched_row$Ctrl_Cost,
      Enr_Ctrl_Effect = enriched_row$Ctrl_Effect,
      Enr_ICER = enriched_row$ICER,
      Enr_Status = enriched_row$Status,
      Pct_Change = pct_change,
      stringsAsFactors = FALSE
    )
  })

  do.call(rbind, rows)
}

#' Format enriched comparison table for display
#'
#' @param comparison_df Data frame from format_enriched_comparison_table()
#' @return Formatted data frame suitable for printing or kable
format_enriched_for_display <- function(comparison_df) {

  display_df <- comparison_df

  display_df$Prevalence <- sprintf("%.1f%%", display_df$Prevalence * 100)

  cost_cols <- grep("^(Base_Cost|Enr_Cost|Enr_Ctrl_Cost)$",
                    names(display_df), value = TRUE)
  for (col in cost_cols) {
    display_df[[col]] <- scales::dollar(display_df[[col]],
                                        prefix = "EUR ", accuracy = 1)
  }

  effect_cols <- grep("^(Base_Effect|Enr_Effect|Enr_Ctrl_Effect)$",
                      names(display_df), value = TRUE)
  for (col in effect_cols) {
    display_df[[col]] <- sprintf("%.3f", display_df[[col]])
  }

  icer_cols <- grep("^(Base_ICER|Enr_ICER)$",
                    names(display_df), value = TRUE)
  for (icer_col in icer_cols) {
    status_col <- gsub("ICER", "Status", icer_col)
    display_df[[icer_col]] <- ifelse(
      display_df[[status_col]] == "Dominated",
      "Dominated",
      ifelse(display_df[[status_col]] == "Reference",
             "--",
             ifelse(is.na(display_df[[icer_col]]) |
                      !is.finite(as.numeric(display_df[[icer_col]])),
                    "--",
                    scales::dollar(as.numeric(display_df[[icer_col]]),
                                   prefix = "EUR ", accuracy = 1)))
    )
  }

  display_df$Pct_Change <- ifelse(
    is.na(display_df$Pct_Change),
    "--",
    sprintf("%+.1f%%", as.numeric(display_df$Pct_Change))
  )

  display_df[, !grepl("^(Base_Status|Enr_Status)$", names(display_df))]
}

# ===============================================================================
# MAIN EXECUTION
# ===============================================================================

cat("\n")
cat(rep("=", 80), "\n", sep = "")
cat("ENRICHED POPULATION COST-EFFECTIVENESS ANALYSIS\n")
cat("Biomarker-positive experimental vs biomarker-positive control\n")
cat(rep("=", 80), "\n", sep = "")

enriched_results <- run_enriched_analysis(verbose = TRUE)

enriched_comparison <- format_enriched_comparison_table(enriched_results)
enriched_display <- format_enriched_for_display(enriched_comparison)

cat("\n")
cat(rep("=", 80), "\n", sep = "")
cat("RESULTS: Base Case vs Enriched Population ICERs\n")
cat("(Base case: vs overall control | Enriched: vs biomarker-positive control)\n")
cat(rep("=", 80), "\n\n")

summary_cols <- c("Biomarker", "Prevalence", "Base_ICER",
                  "Enr_ICER", "Pct_Change")
print(enriched_display[, summary_cols], row.names = FALSE)

cat("\n")
cat(rep("=", 80), "\n", sep = "")
cat("DETAILED RESULTS: Enriched Cohort Costs and QALYs\n")
cat(rep("=", 80), "\n\n")

cat("Enriched experimental (biomarker-positive on FLOX + nivolumab) vs\n")
cat("Enriched control (biomarker-positive on FLOX only)\n\n")

detail_cols <- c("Biomarker", "Enr_Cost", "Enr_Effect",
                 "Enr_Ctrl_Cost", "Enr_Ctrl_Effect", "Enr_ICER")
print(enriched_display[, detail_cols], row.names = FALSE)

cat("\nNote: Enriched population uses biomarker-positive patients for BOTH arms.\n")
cat("Experimental arm: biomarker-positive on FLOX + nivolumab.\n")
cat("Control arm: biomarker-positive on FLOX only (counterfactual).\n")
cat("Both arms incur the biomarker test cost.\n")
