# ===============================================================================
# ENRICHED POPULATION COST-EFFECTIVENESS ANALYSIS
# ===============================================================================
# Calculates ICERs for a "ceiling scenario" where only biomarker-positive
# patients are considered. For each biomarker strategy:
#   - Experimental arm: biomarker-positive patients on FLOX + nivolumab
#   - Control arm: biomarker-positive patients on FLOX only
#
# This is an apples-to-apples comparison within the enriched (biomarker+) cohort,
# as in a biomarker-enriched trial design where only positive patients are enrolled.
#
# Biomarker-positive experimental curves already exist in l_params_base.
# Biomarker-positive control curves are generated by predicting from the fitted
# survival models for positive patients assigned to the control treatment.
#
# Runs across all three model structures (A=joint, B=focused, C=separate)
# and compares enriched ICERs to base case ICERs.
#
# Prerequisites:
#   - 02_setup_and_global_variables.R (global vars)
#   - 03_biomarker_strategies.R (biomarker definitions)
#   - 06/07 are re-sourced automatically by run_basecase_for_structure()
# ===============================================================================

# Load required packages
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(here, dampack, dplyr, scales, flexsurv)

# Load functions
source(here::here("scripts/R/functions/model_fun.R"))
source(here::here("scripts/R/functions/calculate_outcomes.R"))
source(here::here("scripts/R/functions/multi_model_cea.R"))
source(here::here("scripts/R/functions/prediction_functions.R"))

# ===============================================================================
# HELPER FUNCTIONS
# ===============================================================================

#' Calculate simple pairwise ICERs (each strategy vs control)
#'
#' @param results Data frame with Strategy, Cost, Effect columns (from model_fun)
#' @return Data frame with columns: Strategy, Cost, Effect, Inc_Cost, Inc_Effect, ICER, Status
calculate_pairwise_icers <- function(results) {
  control_cost <- results$Cost[results$Strategy == "control"]
  control_effect <- results$Effect[results$Strategy == "control"]

  pairwise_df <- data.frame(
    Strategy = results$Strategy,
    Cost = results$Cost,
    Effect = results$Effect,
    Inc_Cost = results$Cost - control_cost,
    Inc_Effect = results$Effect - control_effect,
    stringsAsFactors = FALSE
  )

  pairwise_df$ICER <- ifelse(
    pairwise_df$Strategy == "control",
    NA_real_,
    pairwise_df$Inc_Cost / pairwise_df$Inc_Effect
  )

  pairwise_df$Status <- ifelse(
    pairwise_df$Strategy == "control",
    "Reference",
    ifelse(pairwise_df$Inc_Cost > 0 & pairwise_df$Inc_Effect <= 0,
           "Dominated",
           ifelse(pairwise_df$Inc_Cost < 0 & pairwise_df$Inc_Effect > 0,
                  "Cost-saving",
                  "Non-dominated"))
  )

  return(pairwise_df)
}

#' Generate survival curves for biomarker-positive patients on control treatment
#'
#' Uses the fitted survival models (available in global env after run_basecase_for_structure)
#' to predict OS and PFS for biomarker-positive patients assigned to control Rx.
#'
#' @param biomarker_name Character: "crp", "tlr", or "tmb_braf"
#' @return List with $os and $pfs vectors (population-averaged survival curves)
generate_enriched_control_curves <- function(biomarker_name) {

  # data_complete, models, time_points are in global env from script 06
  ctrl_rx <- levels(data_complete$Rx)[1]

  # Filter to biomarker-positive patients
  pos_data <- data_complete[as.numeric(as.character(data_complete[[biomarker_name]])) == 1, ]
  pos_data$Rx <- factor(ctrl_rx, levels = levels(data_complete$Rx))

  # Get the appropriate fitted model
  if (uses_per_strategy_formulas()) {
    # Models B/C: biomarker-specific model
    model_os <- models$best_fit[[biomarker_name]]$os
    model_pfs <- models$best_fit[[biomarker_name]]$pfs
  } else {
    # Model A: shared model
    model_os <- models$best_fit$os
    model_pfs <- models$best_fit$pfs
  }

  # Predict survival for biomarker-positive patients on control
  os_pred <- predict(model_os, newdata = pos_data, type = "survival", times = time_points)
  pfs_pred <- predict(model_pfs, newdata = pos_data, type = "survival", times = time_points)

  # Extract and population-average
  os_matrix <- extract_all_survival_probabilities(os_pred)
  pfs_matrix <- extract_all_survival_probabilities(pfs_pred)

  list(
    os = rowMeans(os_matrix, na.rm = TRUE),
    pfs = rowMeans(pfs_matrix, na.rm = TRUE)
  )
}

#' Compute state occupancy from survival curves with constraints
#'
#' @param os OS survival vector
#' @param pfs PFS survival vector
#' @param label Label for warning messages
#' @return List with p_pf, p_p, p_d vectors
compute_state_occupancy <- function(os, pfs, label = "") {
  # Enforce PFS <= OS
  pfs <- pmin(pfs, os)

  p_pf <- pfs
  p_p <- pmax(os - pfs, 0)
  p_d <- 1 - os

  # Force initial state: 100% progression-free
  p_pf[1] <- 1.0
  p_p[1] <- 0.0
  p_d[1] <- 0.0

  list(p_pf = p_pf, p_p = p_p, p_d = p_d)
}

#' Run enriched population analysis for a specific model structure
#'
#' For each biomarker, computes:
#'   - Enriched experimental: biomarker+ patients on experimental treatment
#'   - Enriched control: biomarker+ patients on standard treatment (new curves)
#'   - Enriched ICER: (exp_cost - ctrl_cost) / (exp_effect - ctrl_effect)
#'
#' @param model_structure Integer (0, 1, or 2)
#' @param verbose Logical, print progress messages
#' @return List with base and enriched results
run_enriched_for_structure <- function(model_structure, verbose = TRUE) {

  # Run base case (re-sources 06+07, populates global env)
  base_result <- run_basecase_for_structure(model_structure, verbose = verbose)
  base_pairwise <- calculate_pairwise_icers(base_result$base_results)

  if (verbose) {
    cat("  Generating enriched population curves (biomarker+ control)...\n")
  }

  # Discount factors
  v_dw_c <- 1 / (1 + l_params_base$dr_costs)^(seq(0, time_horizon) / 52)
  v_dw_e <- 1 / (1 + l_params_base$dr_effects)^(seq(0, time_horizon) / 52)

  biomarkers <- get_biomarkers()
  enriched_rows <- list()

  for (biomarker in biomarkers) {

    # --- Enriched experimental arm (existing curves) ---
    os_exp <- l_params_base$p_os[[paste0(biomarker, "_pos_OS")]]
    pfs_exp <- l_params_base$p_pfs[[paste0(biomarker, "_pos_PFS")]]
    states_exp <- compute_state_occupancy(os_exp, pfs_exp, paste0(biomarker, "+ exp"))

    exp_outcomes <- calculate_outcomes(
      params = l_params_base,
      p_pf = states_exp$p_pf,
      p_p = states_exp$p_p,
      p_d = states_exp$p_d,
      treatment_type = "experimental",
      biomarker = biomarker,
      v_dw_c = v_dw_c,
      v_dw_e = v_dw_e,
      cl = cl
    )

    # --- Enriched control arm (new curves: biomarker+ on FLOX) ---
    ctrl_curves <- generate_enriched_control_curves(biomarker)
    states_ctrl <- compute_state_occupancy(ctrl_curves$os, ctrl_curves$pfs,
                                           paste0(biomarker, "+ ctrl"))

    ctrl_outcomes <- calculate_outcomes(
      params = l_params_base,
      p_pf = states_ctrl$p_pf,
      p_p = states_ctrl$p_p,
      p_d = states_ctrl$p_d,
      treatment_type = "standard",
      biomarker = biomarker,
      v_dw_c = v_dw_c,
      v_dw_e = v_dw_e,
      cl = cl
    )

    # --- Compute enriched ICER ---
    inc_cost <- exp_outcomes$costs_total - ctrl_outcomes$costs_total
    inc_effect <- exp_outcomes$qalys_total - ctrl_outcomes$qalys_total

    if (inc_cost > 0 & inc_effect <= 0) {
      status <- "Dominated"
    } else if (inc_cost < 0 & inc_effect > 0) {
      status <- "Cost-saving"
    } else {
      status <- "Non-dominated"
    }

    icer_val <- inc_cost / inc_effect

    enriched_rows[[biomarker]] <- data.frame(
      Strategy = biomarker,
      Cost = exp_outcomes$costs_total,
      Effect = exp_outcomes$qalys_total,
      Ctrl_Cost = ctrl_outcomes$costs_total,
      Ctrl_Effect = ctrl_outcomes$qalys_total,
      Inc_Cost = inc_cost,
      Inc_Effect = inc_effect,
      ICER = icer_val,
      Status = status,
      stringsAsFactors = FALSE
    )
  }

  enriched_pairwise <- do.call(rbind, enriched_rows)
  rownames(enriched_pairwise) <- NULL

  if (verbose) {
    cat("  Enriched analysis complete.\n")
  }

  return(list(
    base_results = base_result$base_results,
    base_pairwise = base_pairwise,
    base_icer_obj = base_result$icer_obj,
    enriched_pairwise = enriched_pairwise,
    model_structure = model_structure
  ))
}

#' Run enriched population analysis for all model structures
#'
#' @param verbose Logical, print progress messages
#' @return Named list of results for each model structure
run_all_enriched_analyses <- function(verbose = TRUE) {

  model_configs <- get_model_configs()
  all_results <- list()

  for (model_name in names(model_configs)) {
    config <- model_configs[[model_name]]

    if (verbose) {
      cat("\n", rep("=", 70), "\n", sep = "")
      cat("ENRICHED ANALYSIS:", config$label, "\n")
      cat(rep("=", 70), "\n", sep = "")
    }

    all_results[[model_name]] <- run_enriched_for_structure(
      model_structure = config$structure,
      verbose = verbose
    )
    all_results[[model_name]]$config <- config
  }

  return(all_results)
}

# ===============================================================================
# FORMATTING FUNCTIONS
# ===============================================================================

#' Format enriched vs base case comparison table
#'
#' @param all_results Named list from run_all_enriched_analyses()
#' @return Data frame with comparison metrics
format_enriched_comparison_table <- function(all_results) {

  model_configs <- get_model_configs()
  biomarkers <- c("crp", "tlr", "tmb_braf")
  biomarker_labels <- c("CRP", "TLR", "TMB/BRAF")

  rows <- list()

  for (i in seq_along(biomarkers)) {
    bm <- biomarkers[i]
    row <- data.frame(Biomarker = biomarker_labels[i], stringsAsFactors = FALSE)

    for (model_name in names(all_results)) {
      result <- all_results[[model_name]]
      sl <- model_configs[[model_name]]$short_label

      base_row <- result$base_pairwise[result$base_pairwise$Strategy == bm, ]
      enriched_row <- result$enriched_pairwise[result$enriched_pairwise$Strategy == bm, ]

      # Base case metrics (vs overall control)
      row[[paste0("Base_Cost_", sl)]] <- base_row$Cost
      row[[paste0("Base_Effect_", sl)]] <- base_row$Effect
      row[[paste0("Base_ICER_", sl)]] <- base_row$ICER
      row[[paste0("Base_Status_", sl)]] <- base_row$Status

      # Enriched metrics (vs biomarker+ control)
      row[[paste0("Enr_Cost_", sl)]] <- enriched_row$Cost
      row[[paste0("Enr_Effect_", sl)]] <- enriched_row$Effect
      row[[paste0("Enr_Ctrl_Cost_", sl)]] <- enriched_row$Ctrl_Cost
      row[[paste0("Enr_Ctrl_Effect_", sl)]] <- enriched_row$Ctrl_Effect
      row[[paste0("Enr_ICER_", sl)]] <- enriched_row$ICER
      row[[paste0("Enr_Status_", sl)]] <- enriched_row$Status

      # Percentage change in ICER (only meaningful when both are non-dominated)
      base_icer <- base_row$ICER
      enr_icer <- enriched_row$ICER
      base_status <- base_row$Status
      enr_status <- enriched_row$Status
      if (base_status == "Non-dominated" && enr_status == "Non-dominated" &&
          !is.na(base_icer) && !is.na(enr_icer) &&
          base_icer != 0 && is.finite(base_icer) && is.finite(enr_icer)) {
        row[[paste0("Pct_Change_", sl)]] <- (enr_icer - base_icer) / abs(base_icer) * 100
      } else {
        row[[paste0("Pct_Change_", sl)]] <- NA_real_
      }
    }

    rows[[i]] <- row
  }

  comparison_df <- do.call(rbind, rows)

  # Add prevalence column
  if (exists("strategies_df")) {
    comparison_df$Prevalence <- sapply(biomarkers, function(bm) {
      strategies_df$prevalence[strategies_df$id == bm]
    })
  } else {
    comparison_df$Prevalence <- NA_real_
  }

  col_order <- c("Biomarker", "Prevalence",
                 setdiff(names(comparison_df), c("Biomarker", "Prevalence")))
  comparison_df <- comparison_df[, col_order]

  return(comparison_df)
}

#' Format enriched comparison table for display
#'
#' @param comparison_df Data frame from format_enriched_comparison_table()
#' @return Formatted data frame suitable for printing or kable
format_enriched_for_display <- function(comparison_df) {

  display_df <- comparison_df

  # Format prevalence
  display_df$Prevalence <- sprintf("%.1f%%", display_df$Prevalence * 100)

  # Format cost columns
  cost_cols <- grep("^(Base_Cost_|Enr_Cost_|Enr_Ctrl_Cost_)", names(display_df), value = TRUE)
  for (col in cost_cols) {
    display_df[[col]] <- scales::dollar(display_df[[col]], prefix = "EUR ", accuracy = 1)
  }

  # Format effect columns
  effect_cols <- grep("^(Base_Effect_|Enr_Effect_|Enr_Ctrl_Effect_)", names(display_df), value = TRUE)
  for (col in effect_cols) {
    display_df[[col]] <- sprintf("%.3f", display_df[[col]])
  }

  # Format ICER columns with status handling
  icer_cols <- grep("^(Base_ICER_|Enr_ICER_)", names(display_df), value = TRUE)
  for (icer_col in icer_cols) {
    status_col <- gsub("ICER", "Status", icer_col)
    if (status_col %in% names(display_df)) {
      display_df[[icer_col]] <- ifelse(
        display_df[[status_col]] == "Dominated",
        "Dominated",
        ifelse(display_df[[status_col]] == "Reference",
               "--",
               ifelse(is.na(display_df[[icer_col]]) | !is.finite(as.numeric(display_df[[icer_col]])),
                      "--",
                      scales::dollar(as.numeric(display_df[[icer_col]]), prefix = "EUR ", accuracy = 1)))
      )
    }
  }

  # Format percentage change columns
  pct_cols <- grep("^Pct_Change_", names(display_df), value = TRUE)
  for (col in pct_cols) {
    display_df[[col]] <- ifelse(
      is.na(display_df[[col]]),
      "--",
      sprintf("%+.1f%%", as.numeric(display_df[[col]]))
    )
  }

  # Remove status columns from display
  display_df <- display_df[, !grepl("^(Base_Status_|Enr_Status_)", names(display_df))]

  return(display_df)
}

# ===============================================================================
# MAIN EXECUTION
# ===============================================================================

cat("\n")
cat(rep("=", 80), "\n", sep = "")
cat("ENRICHED POPULATION COST-EFFECTIVENESS ANALYSIS\n")
cat("Biomarker+ experimental vs biomarker+ control (enriched trial design)\n")
cat(rep("=", 80), "\n", sep = "")

# Store original MODEL_STRUCTURE to restore later
original_model_structure <- MODEL_STRUCTURE

# Run all enriched analyses across all model structures
all_enriched_results <- run_all_enriched_analyses(verbose = TRUE)

# Restore original MODEL_STRUCTURE
MODEL_STRUCTURE <<- original_model_structure

# Format comparison table
enriched_comparison <- format_enriched_comparison_table(all_enriched_results)
enriched_display <- format_enriched_for_display(enriched_comparison)

# Print results
cat("\n")
cat(rep("=", 80), "\n", sep = "")
cat("RESULTS: Base Case vs Enriched Population ICERs\n")
cat("(Base case: vs overall control | Enriched: vs biomarker+ control)\n")
cat(rep("=", 80), "\n\n")

model_configs <- get_model_configs()
for (model_name in names(all_enriched_results)) {
  config <- model_configs[[model_name]]
  sl <- config$short_label

  cat("--- ", config$label, " ---\n")

  summary_cols <- c("Biomarker", "Prevalence",
                    paste0("Base_ICER_", sl),
                    paste0("Enr_ICER_", sl),
                    paste0("Pct_Change_", sl))
  available_cols <- summary_cols[summary_cols %in% names(enriched_display)]
  print(enriched_display[, available_cols], row.names = FALSE)
  cat("\n")
}

# Print detailed cost/QALY breakdown
cat("\n")
cat(rep("=", 80), "\n", sep = "")
cat("DETAILED RESULTS: Enriched Cohort Costs and QALYs\n")
cat(rep("=", 80), "\n\n")

for (model_name in names(all_enriched_results)) {
  config <- model_configs[[model_name]]
  sl <- config$short_label

  cat("--- ", config$label, " ---\n")
  cat("  Enriched experimental (biomarker+ on FLOX+nivo) vs\n")
  cat("  Enriched control (biomarker+ on FLOX only)\n\n")

  detail_cols <- c("Biomarker",
                   paste0("Enr_Cost_", sl), paste0("Enr_Effect_", sl),
                   paste0("Enr_Ctrl_Cost_", sl), paste0("Enr_Ctrl_Effect_", sl),
                   paste0("Enr_ICER_", sl))
  available_cols <- detail_cols[detail_cols %in% names(enriched_display)]
  print(enriched_display[, available_cols], row.names = FALSE)
  cat("\n")
}

cat("\nNote: Enriched population uses biomarker-positive patients for BOTH arms.\n")
cat("Experimental arm: biomarker+ on FLOX + nivolumab.\n")
cat("Control arm: biomarker+ on FLOX only (counterfactual).\n")
cat("Both arms incur the biomarker test cost.\n")
